#######################################################################################
# Book settings
title : Programmering og modellering
author: Andreas Haraldsrud
logo: 'datalogo.png'

# Information about where the book exists on the web
description: >-
  Nettsider for Programmering og modellering X

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : false

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/andreasdh/programmering-og-modellering
  path_to_book                : "mini_book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
